services:
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # For Jupyter Notebook/Lab
      - "6006:6006"  # For TensorBoard
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket
    environment:
      - DISPLAY=${DISPLAY}  # Pass the host's display variable
      - QT_X11_NO_MITSHM=1  # Fix shared memory issues
    runtime: nvidia  # If using GPU
