name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9             # Compatible with TensorFlow 2.10 and CUDA 11.8
  - jupyterlab
  - pandas
  - scipy
  - scikit-learn
  - numpy
  - matplotlib
  - statsmodels
  - seaborn
  - xgboost
  - cudnn          # Required for TensorFlow
  - tensorflow=2.10        # Compatible with Python 3.9 and CUDA 11.8
  - pip:
      - ipywidgets
